import Foundation
import WhoopCore

// Command Line Tools omit XCTest. This harness runs the protocol and durability checks there.
func require(_ condition: Bool, _ message: String) { precondition(condition, message) }
let packet = try WhoopWire.heartRate(Data([0x10, 0x3e, 0x19, 0x04]))
require(packet.0 == 62 && packet.1 == [1024.4140625], "published HR packet")
let extra = try WhoopWire.heartRate(Data([0x19, 0x2c, 0x01, 0, 0, 0, 4, 0, 2]))
require(extra.0 == 300 && extra.1 == [1000, 500], "optional HR fields")
require((try? WhoopWire.heartRate(Data([0x10, 60, 1]))) == nil, "reject truncated RR")
require(WhoopWire.crc32(Array("123456789".utf8)) == 0xcbf43926, "CRC32 vector")
require(WhoopWire.crc8(Array("123456789".utf8)) == 0xf4, "CRC8 vector")
let frame = WhoopWire.command(22, sequence: 1, payload: [0])
var parser = Reassembler()
require(parser.append(frame.prefix(5)).isEmpty, "fragment buffering")
require(parser.append(frame.dropFirst(5) + frame) == [frame, frame], "coalesced frames")
var corrupt = frame; corrupt[7] ^= 1
require((try? Frame(corrupt)) == nil, "CRC rejection")
var battery = BatteryAlerts()
require(battery.observe(19) == 20, "20 percent alert")
require(battery.observe(18) == nil && battery.observe(21) == nil, "no duplicate alert")
require(battery.observe(9) == 10, "10 percent alert")
battery = try JSONDecoder().decode(BatteryAlerts.self, from: JSONEncoder().encode(battery))
require(battery.observe(9) == nil, "alert state survives restart")
require(battery.observe(80) == nil && battery.observe(8) == 10 && battery.observe(8) == nil, "recharge rearming")
let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
defer { try? FileManager.default.removeItem(at: directory) }
let url = directory.appendingPathComponent("test.sqlite")
var record = Capture(deviceId: "test", sessionId: "one", source: "history", raw: Data([1,2,3]))
record.useHistoricalIdentity()
do {
    let store = try CaptureStore(url: url); try store.insert(record); try store.insert(record)
    require(try store.pending().count == 1, "deduplicate replay")
}
let reopened = try CaptureStore(url: url)
require(try reopened.pending().count == 1, "durable reopen")
try reopened.acknowledge([record.id]); require(try reopened.pending().isEmpty, "upload acknowledgement")
let acknowledged = try reopened.exportStatus()
require(acknowledged.pending == 0 && acknowledged.lastAcknowledged != nil, "durable export status")
let reopenedAgain = try CaptureStore(url: url)
require(try reopenedAgain.exportStatus().lastAcknowledged == acknowledged.lastAcknowledged, "ack timestamp survives restart")
var evidence = BatteryEvidence()
let observed = Date(timeIntervalSince1970: 1700000000)
evidence.observe(100, custom: false, at: observed)
require(evidence.verified(at: observed) == nil, "first standard battery is unverified")
evidence.observe(9.6, custom: true, at: observed.addingTimeInterval(1))
require(evidence.verified(at: observed.addingTimeInterval(1)) == nil, "reject measured battery disagreement")
evidence.observe(9, custom: false, at: observed.addingTimeInterval(2))
require(evidence.verified(at: observed.addingTimeInterval(2))?.percent == 9.6, "accept whole-percent battery cross-check")
require(evidence.verified(at: observed.addingTimeInterval(700)) == nil, "stale battery is not verified")
evidence.observe(9, custom: false, at: observed.addingTimeInterval(60))
require(evidence.verified(at: observed.addingTimeInterval(60)) == nil, "do not pair readings from different cycles")
var response = [UInt8](WhoopWire.command(26, sequence: 1, payload: [1, 1, 96, 0]))
response[4] = 0x24
response.replaceSubrange((response.count - 4)..<response.count, with: WhoopWire.littleEndian(WhoopWire.crc32(Array(response[4..<(response.count - 4)]))))
require(WhoopWire.customBattery(try Frame(Data(response))) == 9.6, "custom battery response scaling")
let rawHR = try WhoopWire.heartRateWords(Data([0x10, 75, 0x0e, 0x03]))
require(rawHR.1 == [782], "preserve observed interval word without assuming units")
var recovery = ConnectionRecovery()
recovery.connected(at: 0); recovery.ready(at: 0)
require(recovery.check(at: 20) == .restartLive, "silent stream gets restarted")
require(recovery.check(at: 35) == .reconnect("telemetry_timeout"), "silent connection gets replaced")
var transfer = HistoryTransfer()
transfer.begin(at: 0); transfer.invalidate()
require(!transfer.running, "corruption/storage failures pause history cursor advances")
print("PASS: battery cross-check/freshness, raw interval preservation, durable export status; plus  protocol vectors, corruption/fragmentation, durable replay, battery thresholds and recharge rearming")
